# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ab.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(503, 600)
        MainWindow.setStyleSheet("background-color: white;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 160, 271, 71))
        self.label.setStyleSheet("QLabel{\n"
"    font-size: 30px;\n"
"    font-family:Arial,Helvetica,sans-serif;\n"
"    \n"
"}")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 300, 261, 61))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    font-family:Arial,Helvetica,sans-serif;\n"
"    font-size: 20px;\n"
"\n"
"    background-color: rgb(200, 137, 85);\n"
"    color: rgb(227, 219, 101);\n"
"    \n"
"    border-radius: 20px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 503, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Formulario Enviado"))
        self.pushButton.setText(_translate("MainWindow", "Voltar"))
