# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formulario.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(410, 531)
        Dialog.setStyleSheet("QDialog{\n"
"    background-color: white;\n"
"    border: none;\n"
"    border-radius: 10px;    \n"
"    \n"
"    background-color: black;\n"
"}")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 110, 81, 31))
        self.label.setStyleSheet("QLabel{\n"
"    color: black;\n"
"    font-family:Arial,Helvetica,sans-serif;\n"
"    font-size: 20px;\n"
"    color: white;\n"
"}")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(100, 110, 291, 31))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border: 1px solid rgb(34, 34, 34);\n"
"    \n"
"    font-family:Arial,Helvetica,sans-serif;\n"
"    font-size: 16px;\n"
"\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 1px solid rgb(0, 120, 215);\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 180, 291, 31))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    border: 1px solid rgb(34, 34, 34);\n"
"    \n"
"    font-family:Arial,Helvetica,sans-serif;\n"
"    font-size: 16px;\n"
"\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 1px solid rgb(0, 120, 215);\n"
"    \n"
"    padding-right: 5px;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 180, 91, 31))
        self.label_2.setStyleSheet("QLabel{\n"
"    color: black;\n"
"    font-family:Arial,Helvetica,sans-serif;\n"
"    font-size: 20px;\n"
"    color: white;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(30, 430, 351, 51))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    border: 1px solid rgb(173, 173, 173);\n"
"    background-color:rgb(225, 225, 225);\n"
"\n"
"    font-family:Arial,Helvetica,sans-serif;\n"
"    \n"
"    color: black;\n"
"    \n"
"    font-size : 20px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 240, 381, 161))
        self.plainTextEdit.setStyleSheet("QPlainTextEdit{\n"
"    border: none;\n"
"    border: 1px solid black;\n"
"    \n"
"    font-family:Arial,Helveti,sans-serif;\n"
"    \n"
"    font-size: 18px;\n"
"\n"
"\n"
"}")
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Nome:"))
        self.label_2.setText(_translate("Dialog", "Telefone:"))
        self.pushButton.setText(_translate("Dialog", "Enviar"))
